// Contenido del resumen normativo. Cada norma: qué es, qué exige, qué hacer,
// cómo la cubre el sistema y qué queda pendiente fuera del sistema.

module.exports.normas = [
  // ============================================================ LEYES Y DECRETOS
  {
    grupo: "Leyes y decretos nacionales",
    code: "LEY-25246",
    titulo: "Ley 25.246 — Encubrimiento y Lavado de Activos de origen delictivo",
    organismo: "Congreso de la Nación / UIF",
    responsable: "Oficial de Cumplimiento PLA/FT",
    que_es: "Es la ley base del sistema argentino de prevención de lavado de activos. Tipifica el delito, crea la Unidad de Información Financiera (UIF) y define quiénes son sujetos obligados a informar (entre ellos entidades financieras, cambiarias y otros actores del sistema de pagos). Fue actualizada por la Ley 27.739 (2024), que reforzó el enfoque basado en riesgo, incorporó nuevos sujetos obligados (por ejemplo, proveedores de servicios de activos virtuales) y el concepto de beneficiario final.",
    exige: [
      "Identificar y conocer a los clientes (debida diligencia) y a sus beneficiarios finales.",
      "Reportar a la UIF toda operación sospechosa (ROS), sin importar el monto.",
      "Mantener absoluta confidencialidad: está prohibido informar al cliente o a terceros que se lo está analizando o reportando (prohibición de \"tipping-off\").",
      "Conservar la documentación de clientes y operaciones durante el plazo legal.",
    ],
    hacer: [
      "Designar formalmente un Oficial de Cumplimiento ante la UIF.",
      "Tener un Manual de Procedimientos PLA/FT aprobado por el directorio y actualizado.",
      "Definir y documentar el circuito de análisis de alertas hasta la decisión de ROS.",
      "Capacitar al personal al menos una vez al año y dejar registro.",
      "Conservar la documentación y los registros de monitoreo durante el plazo legal (en general, 10 años).",
      "Instruir a atención al cliente para no revelar motivos de bloqueos o análisis PLA/FT.",
    ],
    sistema: "Detecta tipologías de lavado (fraccionamiento, cuenta puente, fan-in / fan-out). Las alertas pasan por un circuito con fundamento obligatorio y escalamiento a Cumplimiento para decidir el ROS. Los motivos de rechazo PLA/FT no se exponen al cliente. La auditoría es inalterable (encadenada por hash).",
    pendiente: [
      "Presentación efectiva del ROS en el sistema de la UIF (el motor registra la decisión, no envía el reporte).",
      "Persistir la auditoría en almacenamiento inmutable con retención de 10 años.",
    ],
  },
  {
    grupo: "Leyes y decretos nacionales",
    code: "LEY-26734",
    titulo: "Ley 26.734 — Financiamiento del Terrorismo",
    organismo: "Congreso de la Nación / UIF",
    responsable: "Oficial de Cumplimiento PLA/FT",
    que_es: "Tipifica el delito de financiamiento del terrorismo en el Código Penal y amplía las facultades de la UIF, incluyendo la posibilidad de congelar administrativamente bienes vinculados. Extiende a FT las obligaciones de prevención que la Ley 25.246 impone para lavado.",
    exige: [
      "Prevenir que la entidad sea utilizada para financiar actividades terroristas.",
      "Reportar sin demora las operaciones sospechosas de financiamiento del terrorismo.",
      "Colaborar con el congelamiento de bienes que disponga la UIF.",
    ],
    hacer: [
      "Controlar clientes, beneficiarios finales y contrapartes contra listas de terrorismo al alta, en cada operación y cada vez que las listas se actualizan.",
      "Tener un procedimiento escrito para coincidencias: bloqueo inmediato, verificación del \"falso positivo\" y reporte a la UIF.",
      "Reportar las sospechas de FT con carácter urgente (plazo mucho más corto que el de lavado).",
    ],
    sistema: "Las reglas CMN-001, CIN-008 y COUT-009 rechazan en tiempo real cualquier operación donde el cliente o la contraparte figure en la lista de sanciones, y generan una alerta CRÍTICA con SLA de 1 hora.",
    pendiente: [
      "Sincronizar automáticamente la lista de sanciones del sistema con RePET y las listas del Consejo de Seguridad de la ONU (hoy la lista es de ejemplo).",
      "Screening de la cartera completa de clientes cuando cambian las listas (proceso batch, fuera del motor en línea).",
    ],
  },
  {
    grupo: "Leyes y decretos nacionales",
    code: "DEC-918-2012",
    titulo: "Decreto 918/2012 — Congelamiento administrativo de bienes vinculados al terrorismo",
    organismo: "Poder Ejecutivo Nacional / UIF",
    responsable: "Oficial de Cumplimiento PLA/FT",
    que_es: "Reglamenta el procedimiento por el cual la UIF puede ordenar el congelamiento administrativo de fondos y bienes de personas o entidades incluidas en las listas del Consejo de Seguridad de la ONU o vinculadas con financiamiento del terrorismo. Se complementa con el RePET (Registro Público de Personas y Entidades vinculadas a actos de Terrorismo y su Financiamiento).",
    exige: [
      "Congelar sin demora los fondos de personas o entidades designadas.",
      "Comunicar de inmediato a la UIF cualquier coincidencia con las listas.",
      "Consultar las listas de manera permanente.",
    ],
    hacer: [
      "Definir quién ejecuta el congelamiento (bloqueo de cuenta y de fondos) y en qué plazo.",
      "Documentar cada coincidencia y su resolución (verdadero o falso positivo).",
      "No devolver fondos al originante cuando corresponde congelarlos: se retienen según el procedimiento.",
    ],
    sistema: "Ante coincidencia, el motor rechaza la operación y genera una alerta CRÍTICA categoría CFT para Cumplimiento. El rechazo impide que los fondos salgan.",
    pendiente: [
      "Integrar con el core bancario la acción de \"congelar cuenta\" (el motor decide sobre la operación, no bloquea saldos).",
      "Revisar el tratamiento de cash-in de personas listadas: el procedimiento debería retener los fondos, no devolverlos.",
    ],
  },

  // ============================================================ UIF
  {
    grupo: "Resoluciones de la UIF",
    code: "UIF-FT",
    titulo: "Resoluciones UIF sobre reporte de FT y congelamiento (Res. UIF 29/2013 y complementarias)",
    organismo: "Unidad de Información Financiera",
    responsable: "Oficial de Cumplimiento PLA/FT",
    que_es: "Reglamentan cómo deben los sujetos obligados reportar operaciones sospechosas de financiamiento del terrorismo y cómo se ejecuta y comunica el congelamiento administrativo de bienes.",
    exige: [
      "Reportar las operaciones sospechosas de FT en plazo abreviado.",
      "Ejecutar el congelamiento y comunicarlo a la UIF en los plazos y por los medios que establece.",
      "Verificar las listas de manera continua.",
    ],
    hacer: [
      "Tener acceso al sistema de reporte de la UIF y personal habilitado para operarlo.",
      "Guardia o esquema de disponibilidad para responder a coincidencias fuera de horario.",
      "Registrar la evidencia de cada consulta y verificación de listas.",
    ],
    sistema: "Alertas de categoría CFT con SLA de 1 hora y severidad CRÍTICA; el historial de la alerta queda registrado con usuario, fecha y fundamento.",
    pendiente: [
      "Esquema de guardia para alertas CRÍTICAS fuera del horario laboral (notificación por mail/SMS).",
    ],
  },
  {
    grupo: "Resoluciones de la UIF",
    code: "UIF-EEFF",
    titulo: "Resolución UIF para Entidades Financieras y Cambiarias (Res. UIF 14/2023 o la que la reemplace)",
    organismo: "Unidad de Información Financiera",
    responsable: "Oficial de Cumplimiento PLA/FT + Directorio",
    que_es: "Es la norma operativa principal de PLA/FT para bancos y entidades cambiarias. Adopta un enfoque basado en riesgo: cada entidad debe identificar y evaluar sus propios riesgos y aplicar medidas proporcionales.",
    exige: [
      "Autoevaluación de riesgos de LA/FT (clientes, productos, canales, geografía), actualizada periódicamente.",
      "Políticas y procedimientos aprobados por el directorio, y un Oficial de Cumplimiento con recursos suficientes.",
      "Debida diligencia del cliente según su riesgo (simplificada, media o reforzada) y definición del perfil transaccional.",
      "Monitoreo de operaciones con reglas parametrizables y análisis de operaciones inusuales.",
      "Reporte de operaciones sospechosas y conservación de la documentación.",
      "Revisión independiente (auditoría) del sistema de prevención.",
    ],
    hacer: [
      "Elaborar y aprobar la autoevaluación de riesgos y usar sus conclusiones para calibrar los parámetros del sistema.",
      "Asignar a cada cliente un nivel de riesgo (BAJO / MEDIO / ALTO) y un perfil transaccional (ingresos declarados).",
      "Documentar la metodología de las reglas de monitoreo y su calibración (backtesting, modo sombra).",
      "Analizar y cerrar cada alerta con fundamento dentro de los plazos internos.",
      "Informar al directorio periódicamente: alertas, ROS, indicadores.",
      "Encargar la revisión independiente anual del sistema de monitoreo.",
    ],
    sistema: "Es la norma con más cobertura (27 reglas): perfil transaccional vs. ingresos declarados, montos atípicos, efectivo, cuentas nuevas, fan-in / fan-out, KYC no verificado, clientes de riesgo alto. Parámetros configurables por canal, reglas en modo sombra, historial de cambios auditado.",
    pendiente: [
      "Cargar el nivel de riesgo y el perfil transaccional real de cada cliente (hoy vienen en la transacción).",
      "Confirmar con Cumplimiento los umbrales de config/parameters.yaml contra la matriz de riesgo.",
      "Reportes periódicos al directorio (se pueden obtener desde las métricas y el historial).",
    ],
  },
  {
    grupo: "Resoluciones de la UIF",
    code: "UIF-PSP",
    titulo: "Resolución UIF para Proveedores de Servicios de Pago que ofrecen cuentas de pago (Res. UIF 76/2019 o la que la reemplace)",
    organismo: "Unidad de Información Financiera",
    responsable: "Oficial de Cumplimiento PLA/FT",
    que_es: "Establece las obligaciones de prevención para las billeteras virtuales y otros PSP que ofrecen cuentas de pago (CVU). Aplica si la entidad opera como PSP o si parte del negocio (cash-in / cash-out, adquirencia) se hace a través de este tipo de cuentas.",
    exige: [
      "Identificación y verificación de identidad de los titulares de cuentas de pago.",
      "Perfil del cliente y monitoreo de ingresos y egresos de fondos.",
      "Controles sobre comercios adheridos (adquirencia) y sus operaciones.",
      "Reporte de operaciones sospechosas.",
    ],
    hacer: [
      "Verificar identidad en el alta (validación biométrica / RENAPER o equivalente).",
      "Limitar operatoria de cuentas sin verificar hasta completar el KYC.",
      "Evaluar el riesgo de los comercios al adherirlos y monitorear su volumen.",
    ],
    sistema: "Reglas de KYC no verificado (CIN-013, COUT-019), comercio nuevo con volumen alto (ACQ-015), comercio bloqueado (ACQ-022), perfil transaccional (CIN-006/007, COUT-015).",
    pendiente: [
      "Proceso de alta de comercios (onboarding) con evaluación de riesgo previa: está fuera del motor.",
    ],
  },
  {
    grupo: "Resoluciones de la UIF",
    code: "UIF-PEP",
    titulo: "Resolución UIF sobre Personas Expuestas Políticamente (Res. UIF 35/2023)",
    organismo: "Unidad de Información Financiera",
    responsable: "Oficial de Cumplimiento PLA/FT",
    que_es: "Define quiénes son Personas Expuestas Políticamente (funcionarios públicos de cierto nivel, sus familiares y allegados cercanos) y qué medidas adicionales deben aplicarse sobre ellas.",
    exige: [
      "Identificar si el cliente es PEP (declaración jurada del cliente y verificación contra fuentes).",
      "Aplicar debida diligencia reforzada: origen de fondos, aprobación de un nivel jerárquico superior para operar, monitoreo más intenso.",
    ],
    hacer: [
      "Incluir la declaración jurada PEP en el alta y en cada actualización de legajo.",
      "Consultar bases de PEP y registrar la verificación.",
      "Marcar al cliente como PEP en el sistema (campo is_pep) para que se apliquen las reglas.",
    ],
    sistema: "Reglas CIN-010 y COUT-020: toda operación relevante de un cliente PEP va a revisión.",
    pendiente: [
      "Circuito de aprobación jerárquica para la relación con clientes PEP (fuera del motor).",
    ],
  },

  // ============================================================ BCRA
  {
    grupo: "Normas del BCRA",
    code: "BCRA-A7724",
    titulo: "Com. \"A\" 7724 — Requisitos mínimos para la gestión y control de los riesgos de tecnología y seguridad de la información",
    organismo: "Banco Central de la República Argentina",
    responsable: "Tecnología + Seguridad de la Información + Riesgos",
    que_es: "Norma del BCRA que fija los requisitos mínimos de gobierno, gestión de riesgos y controles para la tecnología y la seguridad de la información de las entidades financieras, incluidos los canales electrónicos y los proveedores de servicios.",
    exige: [
      "Gobierno y gestión de riesgos de tecnología y seguridad de la información.",
      "Control de accesos, trazabilidad de acciones y protección de registros.",
      "Gestión formal de cambios en sistemas.",
      "Continuidad operativa y gestión de incidentes.",
      "Control de proveedores y servicios en la nube.",
      "Monitoreo de fraude en canales electrónicos.",
    ],
    hacer: [
      "Incluir el sistema de monitoreo en el inventario de activos críticos y en el análisis de riesgos.",
      "Poner la consola detrás de un login con usuarios nominales y permisos por rol (hoy es de acceso libre en modo desarrollo).",
      "Formalizar el procedimiento de cambios de reglas: quién propone, quién aprueba, quién activa.",
      "Definir el plan de continuidad: qué pasa si el motor no responde (ya existe la política de contingencia; hay que probarla).",
      "Enviar logs y métricas al SOC; definir alertas técnicas.",
      "Si se despliega en la nube: evaluación del proveedor según la normativa.",
    ],
    sistema: "Auditoría encadenada por hash y verificable, versión de configuración asociada a cada decisión, historial de cambios con usuario y valores anteriores, validación antes de cada cambio, API keys separadas (sistemas / administración), política de contingencia por canal, métricas para el SOC.",
    pendiente: [
      "Autenticación de usuarios (SSO) y permisos por rol en la consola.",
      "Pruebas documentadas de continuidad y de recuperación.",
      "Persistencia de alertas y auditoría en base de datos / almacenamiento inmutable.",
    ],
  },
  {
    grupo: "Normas del BCRA",
    code: "BCRA-PUSF",
    titulo: "Texto ordenado \"Protección de los usuarios de servicios financieros\"",
    organismo: "Banco Central de la República Argentina",
    responsable: "Prevención de Fraude + Atención al Cliente + Legales",
    que_es: "Conjunto de normas del BCRA que protege a los usuarios del sistema financiero: información clara, trato digno, gestión de reclamos y medidas de seguridad frente a fraudes (ingeniería social, robo de identidad, toma de cuentas).",
    exige: [
      "Implementar mecanismos de prevención y detección de fraude que protejan al usuario.",
      "Gestionar reclamos (incluidos los desconocimientos de operaciones) dentro de los plazos establecidos.",
      "Informar al usuario de manera clara, sin afectar la confidencialidad de PLA/FT.",
    ],
    hacer: [
      "Revisar las comunicaciones vigentes del BCRA sobre seguridad en canales electrónicos y sobre reintegro de fondos ante fraudes, y adecuar los límites y controles.",
      "Definir qué ve el cliente cuando una operación queda retenida o rechazada por fraude (mensaje, canal de contacto).",
      "Conectar las alertas de fraude con el circuito de reclamos y desconocimientos.",
      "Medir el fraude no detectado (reclamos sin alerta previa) para mejorar las reglas.",
    ],
    sistema: "Reglas de toma de cuenta (COUT-004: dispositivo nuevo + beneficiario nuevo + sesión corta), beneficiario nuevo, cuentas mula, egresos nocturnos, límites diarios y dispositivos bloqueados (12 reglas).",
    pendiente: [
      "Notificación al cliente en tiempo real (push/SMS) cuando se retiene una operación.",
      "Integración con la gestión de reclamos.",
    ],
  },
  {
    grupo: "Normas del BCRA",
    code: "BCRA-TRANSF",
    titulo: "Texto ordenado \"Sistema Nacional de Pagos — Transferencias\"",
    organismo: "Banco Central de la República Argentina",
    responsable: "Operaciones + Prevención de Fraude",
    que_es: "Regula las transferencias inmediatas (CBU/CVU/alias), el DEBIN y los pagos con QR interoperable (Transferencias 3.0). Las transferencias inmediatas se acreditan en segundos y son irrevocables.",
    exige: [
      "Acreditación inmediata y disponibilidad permanente del servicio.",
      "Mostrar al ordenante los datos del destinatario antes de confirmar.",
      "Cumplir los esquemas de límites, controles y resolución de desconocimientos entre entidades.",
    ],
    hacer: [
      "Evaluar el riesgo ANTES de ejecutar la transferencia: una vez enviada no se puede revertir.",
      "Asegurar que el tiempo de respuesta del motor no afecte la experiencia (objetivo < 100 ms).",
      "Definir el procedimiento con otras entidades ante transferencias fraudulentas (pedido de bloqueo en destino).",
    ],
    sistema: "El motor responde en tiempo real (≈ 1 ms promedio medido, objetivo configurado 100 ms) y se consulta antes de ejecutar cada cash-out. Regla COUT-003 (beneficiario nuevo con monto alto) y el resto del bloque de cash-out.",
    pendiente: [
      "Integración con el autorizador de transferencias para retener la operación cuando la decisión es REVISAR.",
    ],
  },

  // ============================================================ INTERNACIONALES
  {
    grupo: "Estándares internacionales",
    code: "PCI-DSS",
    titulo: "PCI DSS — Payment Card Industry Data Security Standard (v4.x)",
    organismo: "PCI Security Standards Council (exigido por las marcas de tarjetas)",
    responsable: "Seguridad de la Información + Adquirencia",
    que_es: "Estándar de seguridad obligatorio para quien almacena, procesa o transmite datos de tarjetas. Es exigido contractualmente por las marcas (Visa, Mastercard, etc.) a adquirentes, procesadores y comercios.",
    exige: [
      "No almacenar datos sensibles de autenticación (código de seguridad, datos de la banda/chip) después de autorizar.",
      "Proteger el número de tarjeta (PAN): enmascarado, tokenizado o cifrado.",
      "Segmentar la red, controlar accesos, registrar y monitorear actividad.",
      "Pruebas de seguridad periódicas y validación anual de cumplimiento según el nivel.",
    ],
    hacer: [
      "Enviar al motor sólo el token de la tarjeta, el BIN y los últimos 4 dígitos (nunca el número completo).",
      "Incluir o excluir formalmente el sistema de monitoreo del alcance PCI (si no recibe PAN, puede quedar fuera).",
      "Mantener la certificación vigente (ROC/SAQ) del entorno de tarjetas.",
    ],
    sistema: "El sistema está diseñado para no recibir el PAN: identifica la tarjeta por token, BIN y últimos 4, y rechaza textos libres con números de tarjeta. Reglas de testeo de tarjetas, CVV inválido, BIN comprometido, banda magnética y carga manual.",
    pendiente: [
      "Confirmar con el QSA el tratamiento del sistema dentro del alcance PCI.",
    ],
  },
  {
    grupo: "Estándares internacionales",
    code: "GAFI-R1",
    titulo: "GAFI Recomendación 1 — Evaluación de riesgos y enfoque basado en riesgo",
    organismo: "Grupo de Acción Financiera Internacional (GAFI / FATF)",
    responsable: "Oficial de Cumplimiento + Riesgos",
    que_es: "Pide a países e instituciones identificar, evaluar y entender sus riesgos de lavado y financiamiento del terrorismo, y asignar recursos en proporción: más controles donde el riesgo es mayor. La normativa UIF la incorpora.",
    exige: [
      "Evaluación de riesgos documentada y actualizada.",
      "Medidas proporcionales al riesgo identificado.",
    ],
    hacer: [
      "Usar la autoevaluación de riesgos para fijar los umbrales por canal y por tipo de cliente.",
      "Revisar la calibración cuando cambia el negocio (nuevos productos, canales, segmentos).",
    ],
    sistema: "Umbrales y acciones diferenciados por canal; nivel de riesgo del cliente como variable (regla CIN-011); parámetros ajustables desde la consola con vista previa de impacto.",
    pendiente: [
      "Diferenciar umbrales por segmento de cliente (RETAIL / PYME / CORPORATE) si la autoevaluación lo requiere.",
    ],
  },
  {
    grupo: "Estándares internacionales",
    code: "GAFI-R6",
    titulo: "GAFI Recomendación 6 — Sanciones financieras dirigidas relacionadas con el terrorismo",
    organismo: "GAFI / FATF",
    responsable: "Oficial de Cumplimiento PLA/FT",
    que_es: "Exige congelar sin demora los fondos de personas y entidades designadas por el Consejo de Seguridad de la ONU, y no ponerles fondos a disposición. En Argentina se implementa con la Ley 26.734, el Decreto 918/2012 y el RePET.",
    exige: [
      "Screening permanente contra listas oficiales.",
      "Congelamiento sin demora y reporte a la autoridad.",
    ],
    hacer: [
      "Automatizar la descarga y actualización de las listas ONU y RePET.",
      "Revisar la calidad del matching (nombres, alias, documentos) para evitar falsos negativos.",
    ],
    sistema: "Screening en tiempo real por CUIT contra la lista de sanciones en cada operación (CMN-001, CIN-008, COUT-009).",
    pendiente: [
      "Matching por nombre y alias (hoy es por CUIT exacto): conviene complementarlo con una herramienta de screening especializada.",
    ],
  },
  {
    grupo: "Estándares internacionales",
    code: "GAFI-R10",
    titulo: "GAFI Recomendación 10 — Debida diligencia del cliente",
    organismo: "GAFI / FATF",
    responsable: "Oficial de Cumplimiento + Onboarding",
    que_es: "Establece que las instituciones deben identificar y verificar a sus clientes y beneficiarios finales, entender el propósito de la relación y hacer un seguimiento continuo de sus operaciones.",
    exige: [
      "Identificar y verificar al cliente y al beneficiario final.",
      "Entender el propósito y la naturaleza de la relación comercial.",
      "Monitoreo continuo y actualización del legajo.",
    ],
    hacer: [
      "Pedir justificación de origen de fondos en depósitos de efectivo relevantes.",
      "Actualizar legajos según el nivel de riesgo (más seguido para riesgo alto).",
    ],
    sistema: "Reglas de depósito de efectivo elevado (CIN-002/003), KYC no verificado, comercios nuevos, MCC de riesgo y montos muy elevados (9 reglas).",
    pendiente: [
      "Circuito para solicitar y registrar la documentación de origen de fondos cuando se dispara la alerta.",
    ],
  },
  {
    grupo: "Estándares internacionales",
    code: "GAFI-R12",
    titulo: "GAFI Recomendación 12 — Personas Expuestas Políticamente",
    organismo: "GAFI / FATF",
    responsable: "Oficial de Cumplimiento PLA/FT",
    que_es: "Pide medidas reforzadas para las PEP: identificarlas, obtener aprobación de la alta gerencia para la relación, establecer el origen de los fondos y monitorearlas de forma intensificada. En Argentina se implementa con la resolución UIF sobre PEP.",
    exige: [
      "Detección de PEP y debida diligencia reforzada.",
    ],
    hacer: [
      "Ver acciones de la resolución UIF sobre PEP (UIF-PEP).",
    ],
    sistema: "Reglas CIN-010 y COUT-020.",
    pendiente: [
      "Ver UIF-PEP.",
    ],
  },
  {
    grupo: "Estándares internacionales",
    code: "GAFI-R19",
    titulo: "GAFI Recomendación 19 — Países de mayor riesgo",
    organismo: "GAFI / FATF",
    responsable: "Oficial de Cumplimiento PLA/FT",
    que_es: "Pide aplicar debida diligencia reforzada a relaciones y operaciones con personas de países que el GAFI identifica como de alto riesgo. El GAFI publica su lista (\"llamado a la acción\" y \"monitoreo intensificado\") tras cada plenario: febrero, junio y octubre.",
    exige: [
      "Medidas reforzadas proporcionales al riesgo de la jurisdicción.",
    ],
    hacer: [
      "Actualizar la lista high_risk_countries del sistema después de cada plenario del GAFI (tres veces por año).",
      "Dejar evidencia de la actualización (fecha y fuente).",
    ],
    sistema: "Reglas ACQ-017, CIN-009 y COUT-010 revisan operaciones con tarjetas, comercios o contrapartes de jurisdicciones de alto riesgo.",
    pendiente: [
      "La lista cargada es de ejemplo: actualizarla con la publicación vigente del GAFI.",
    ],
  },
  {
    grupo: "Estándares internacionales",
    code: "GAFI-R20",
    titulo: "GAFI Recomendación 20 — Reporte de operaciones sospechosas",
    organismo: "GAFI / FATF",
    responsable: "Oficial de Cumplimiento PLA/FT",
    que_es: "Obliga a reportar de inmediato a la unidad de inteligencia financiera (en Argentina, la UIF) toda operación que se sospeche vinculada con lavado o financiamiento del terrorismo.",
    exige: [
      "Reporte oportuno de operaciones sospechosas.",
      "Confidencialidad sobre el reporte.",
    ],
    hacer: [
      "Medir el tiempo desde la alerta hasta la decisión de ROS y mantenerlo dentro de los plazos legales.",
      "Documentar por qué una alerta NO se reportó (cierre sin ROS fundamentado).",
    ],
    sistema: "Tipologías de fan-in, fan-out, cuenta puente y fraccionamiento (6 reglas); flujo de alertas con decisión \"ROS presentado\" o \"Cerrada sin ROS\", fundamento obligatorio y control de 4 ojos.",
    pendiente: [
      "Tablero de plazos: tiempo entre la operación, la alerta y el ROS.",
    ],
  },
];

module.exports.checklist = [
  ["Designar Oficial de Cumplimiento y aprobar el Manual de Procedimientos PLA/FT", "LEY-25246, UIF-EEFF", "Directorio", "No"],
  ["Elaborar la autoevaluación de riesgos LA/FT y calibrar los umbrales del sistema", "UIF-EEFF, GAFI-R1", "Cumplimiento + Riesgos", "Parcial"],
  ["Cargar nivel de riesgo, perfil transaccional y condición PEP de cada cliente", "UIF-EEFF, UIF-PEP, GAFI-R10", "Onboarding", "Parcial"],
  ["Sincronizar listas de sanciones con RePET y ONU (automático)", "LEY-26734, DEC-918-2012, GAFI-R6", "Cumplimiento + Tecnología", "Parcial"],
  ["Actualizar la lista de países GAFI tras cada plenario (feb/jun/oct)", "GAFI-R19", "Cumplimiento", "Parcial"],
  ["Procedimiento de congelamiento integrado con el core bancario", "DEC-918-2012, UIF-FT", "Operaciones", "No"],
  ["Monitoreo en tiempo real con reglas parametrizables", "UIF-EEFF, UIF-PSP, BCRA-TRANSF", "Prevención de Fraude", "Sí"],
  ["Circuito de alertas con fundamento, escalamiento y 4 ojos para ROS", "LEY-25246, GAFI-R20", "Cumplimiento", "Sí"],
  ["Presentación del ROS en el sistema de la UIF", "LEY-25246, UIF-FT, GAFI-R20", "Oficial de Cumplimiento", "No"],
  ["Auditoría inalterable y conservación por 10 años", "LEY-25246, BCRA-A7724", "Tecnología", "Parcial"],
  ["Login con usuarios nominales y permisos por rol en la consola", "BCRA-A7724", "Tecnología / Seguridad", "No"],
  ["Procedimiento formal de cambios de reglas (propuesta, aprobación, activación)", "BCRA-A7724", "Fraude + Cumplimiento", "Parcial"],
  ["Pruebas del plan de continuidad del motor", "BCRA-A7724", "Tecnología", "Parcial"],
  ["Notificación al cliente y conexión con la gestión de reclamos", "BCRA-PUSF", "Atención al Cliente", "No"],
  ["Confirmar alcance PCI DSS del sistema con el QSA", "PCI-DSS", "Seguridad de la Información", "Parcial"],
  ["Capacitación anual del personal y revisión independiente del sistema", "UIF-EEFF", "Cumplimiento + Auditoría", "No"],
];

module.exports.glosario = [
  ["BCRA", "Banco Central de la República Argentina."],
  ["UIF", "Unidad de Información Financiera: recibe y analiza los reportes de operaciones sospechosas."],
  ["GAFI / FATF", "Grupo de Acción Financiera Internacional: organismo que fija los estándares mundiales de PLA/FT."],
  ["PLA/FT", "Prevención del Lavado de Activos y del Financiamiento del Terrorismo."],
  ["ROS", "Reporte de Operación Sospechosa que se presenta ante la UIF."],
  ["DDC / KYC", "Debida diligencia del cliente / \"conozca a su cliente\": identificar, verificar y conocer al cliente."],
  ["PEP", "Persona Expuesta Políticamente."],
  ["RePET", "Registro Público de Personas y Entidades vinculadas a actos de Terrorismo y su Financiamiento."],
  ["Oficial de Cumplimiento", "Responsable designado ante la UIF por el cumplimiento de las obligaciones PLA/FT."],
  ["Tipping-off", "Revelar al cliente o a terceros que se lo está analizando o reportando. Está prohibido."],
  ["Cuenta puente / mula", "Cuenta usada para recibir fondos y retirarlos rápidamente, cortando el rastro del dinero."],
  ["Fraccionamiento", "Dividir una operación en varias más chicas para no superar un umbral de control."],
  ["Modo sombra", "Estado de una regla que se evalúa y registra, pero no afecta la decisión: sirve para calibrarla."],
  ["PAN", "Número completo de la tarjeta. El sistema nunca lo recibe."],
];
